- name: Build with dotnet
  run: |
    dotnet restore
    dotnet build --configuration Release

- name: Run tests
  run: dotnet test --no-build --verbosity normal

- name: Publish
  run: dotnet publish BankingApi/BankingApi.csproj -c Release -o ./publish
